---
title: "Your project"
author: "Elin Waring"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Your project}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Questions you need to answer in order to make a good
poster. 

Make a copy of this file and fill it out as you are working. 



*What overall topic are you studying? *  


*What round of the RSS data deals with that topic?*  
 
*What are the specific variable names for that topic?*  

*What are the actual survey questions for those variables?*  

*What independent variables do you think will be 
related to someone's answer to those questions?*  

*What are the names of the variables in the data 
set that measure you independent variables?*  

*Are there specific groups of the popularion you are focusing on?*

*What have researchers said about this topic?*  




## How to make your own copy of this file.

Click on:

File > New > Rmarkdown  

On the popup select "From Template."  

Look on the list of templates for the icorp26
template called "Your Project."

Save the file. To be organized, save it in a folder
called rmarkown.

