# rss7 Codebook

    ## # Attaching packages: easystats 0.7.6
    ## ✔ bayestestR  0.18.1   ✔ correlation 0.8.8 
    ## ✔ datawizard  1.3.1    ✔ effectsize  1.0.3 
    ## ✔ insight     1.5.2    ✔ modelbased  0.16.0
    ## ✔ performance 0.17.1   ✔ parameters  0.29.2
    ## ✔ report      0.6.4    ✔ see         0.14.1

    ## Warning: Following 3 columns were empty and have been removed:
    ##   P1_CALWT, P2_CALWT and WEIGHT

| ID | Name | Label | Type | Missings | Values | N |
|:---|:---|:---|:---|---:|---:|---:|
| 1 | HIS_GENERAL | Self-reported health status | categorical | 10 (0.1%) | Excellent | 697 (8.6%) |
|  |  |  |  |  | Very good | 2843 (35.1%) |
|  |  |  |  |  | Good | 3220 (39.7%) |
|  |  |  |  |  | Fair | 1113 (13.7%) |
|  |  |  |  |  | Poor | 235 (2.9%) |
|  |  |  |  |  |  |  |
| 2 | LIF_GENERAL | Self-reported life satisfaction | categorical | 99 (1.2%) | Very satisfied | 2075 (25.9%) |
|  |  |  |  |  | Satisfied | 4849 (60.5%) |
|  |  |  |  |  | Dissatisfied | 947 (11.8%) |
|  |  |  |  |  | Very dissatisfied | 148 (1.8%) |
|  |  |  |  |  |  |  |
| 3 | CHR_HYPEV | Ever been told you had hypertension | categorical | 38 (0.5%) | No | 5013 (62.0%) |
|  |  |  |  |  | Yes | 3067 (38.0%) |
|  |  |  |  |  |  |  |
| 4 | CHR_HYPSTILL | Still have hypertension | categorical | 5068 (62.4%) | No | 527 (17.3%) |
|  |  |  |  |  | Yes | 2523 (82.7%) |
|  |  |  |  |  |  |  |
| 5 | CHR_CHLEV | Ever been told you had high cholesterol | categorical | 136 (1.7%) | No | 4920 (61.6%) |
|  |  |  |  |  | Yes | 3062 (38.4%) |
|  |  |  |  |  |  |  |
| 6 | CHR_CHLSTILL | Still have high cholesterol | categorical | 5084 (62.6%) | No | 861 (28.4%) |
|  |  |  |  |  | Yes | 2173 (71.6%) |
|  |  |  |  |  |  |  |
| 7 | CHR_CAREV | Ever been told you had cardiovascular disease | categorical | 37 (0.5%) | No | 7305 (90.4%) |
|  |  |  |  |  | Yes | 776 (9.6%) |
|  |  |  |  |  |  |  |
| 8 | CHR_CARSTILL | Still have cardiovascular disease | categorical | 7356 (90.6%) | No | 159 (20.9%) |
|  |  |  |  |  | Yes | 603 (79.1%) |
|  |  |  |  |  |  |  |
| 9 | CHR_OBEV | Ever been told you had obesity | categorical | 50 (0.6%) | No | 5903 (73.2%) |
|  |  |  |  |  | Yes | 2165 (26.8%) |
|  |  |  |  |  |  |  |
| 10 | CHR_OBSTILL | Still have obesity | categorical | 5963 (73.5%) | No | 564 (26.2%) |
|  |  |  |  |  | Yes | 1591 (73.8%) |
|  |  |  |  |  |  |  |
| 11 | CHR_SLAPEV | Ever been told you had sleep apnea | categorical | 66 (0.8%) | No | 6782 (84.2%) |
|  |  |  |  |  | Yes | 1270 (15.8%) |
|  |  |  |  |  |  |  |
| 12 | CHR_SLAPSTILL | Still have sleep apnea | categorical | 6862 (84.5%) | No | 270 (21.5%) |
|  |  |  |  |  | Yes | 986 (78.5%) |
|  |  |  |  |  |  |  |
| 13 | CHR_CANEV | Ever been told you had cancer | categorical | 56 (0.7%) | No | 7047 (87.4%) |
|  |  |  |  |  | Yes | 1015 (12.6%) |
|  |  |  |  |  |  |  |
| 14 | CHR_COPDEV | Ever been told you had C.O.P.D. | categorical | 84 (1.0%) | No | 7546 (93.9%) |
|  |  |  |  |  | Yes | 488 (6.1%) |
|  |  |  |  |  |  |  |
| 15 | CHR_ASEV | Ever been told you had asthma | categorical | 61 (0.8%) | No | 6703 (83.2%) |
|  |  |  |  |  | Yes | 1354 (16.8%) |
|  |  |  |  |  |  |  |
| 16 | CHR_ASTILL | Still have asthma | categorical | 6774 (83.4%) | No | 547 (40.7%) |
|  |  |  |  |  | Yes | 797 (59.3%) |
|  |  |  |  |  |  |  |
| 17 | CHR_AS12M | Past 12 months, asthma attack | categorical | 7325 (90.2%) | No | 380 (47.9%) |
|  |  |  |  |  | Yes | 413 (52.1%) |
|  |  |  |  |  |  |  |
| 18 | DIB_PREDIB | Ever been told you had prediabetes | categorical | 94 (1.2%) | No | 5858 (73.0%) |
|  |  |  |  |  | Yes | 2166 (27.0%) |
|  |  |  |  |  |  |  |
| 19 | DIB_GESDIB | Ever been told you had gestational diabetes | categorical | 3927 (48.4%) | No | 3815 (91.0%) |
|  |  |  |  |  | Yes | 376 (9.0%) |
|  |  |  |  |  |  |  |
| 20 | DIB_DIBEV | Ever been told you had diabetes | categorical | 47 (0.6%) | No | 7070 (87.6%) |
|  |  |  |  |  | Yes | 1001 (12.4%) |
|  |  |  |  |  |  |  |
| 21 | DIB_DIBSTILL | Still have diabetes | categorical | 7121 (87.7%) | No | 107 (10.7%) |
|  |  |  |  |  | Yes | 890 (89.3%) |
|  |  |  |  |  |  |  |
| 22 | DIB_PDIBSTILL | Still have prediabetes | categorical | 6709 (82.6%) | No | 604 (42.9%) |
|  |  |  |  |  | Yes | 805 (57.1%) |
|  |  |  |  |  |  |  |
| 23 | DIB_DIBTYPE_R | RECODE: Diabetes Type | categorical | 7275 (89.6%) | Type 1 or some other type | 96 (11.4%) |
|  |  |  |  |  | Type 2 | 747 (88.6%) |
|  |  |  |  |  |  |  |
| 24 | SOC_ERRANDS | Difficulty doing errands alone due to physical, mental, or emotional condition | categorical | 20 (0.2%) | No difficulty | 6440 (79.5%) |
|  |  |  |  |  | Some difficulty | 1238 (15.3%) |
|  |  |  |  |  | A lot of difficulty | 331 (4.1%) |
|  |  |  |  |  | Cannot do this at all | 89 (1.1%) |
|  |  |  |  |  |  |  |
| 25 | SOC_PARACTIV | Difficulty participating in social activities due to physical, mental, or emotional condition | categorical | 79 (1.0%) | No difficulty | 5840 (72.6%) |
|  |  |  |  |  | Some difficulty | 1597 (19.9%) |
|  |  |  |  |  | A lot of difficulty | 491 (6.1%) |
|  |  |  |  |  | Cannot do this at all | 111 (1.4%) |
|  |  |  |  |  |  |  |
| 26 | SOC_PARACTIV_R | RECODE: Difficulty participating in social activities due to physical, mental, or emotional condition | categorical | 79 (1.0%) | No difficulty | 5840 (72.6%) |
|  |  |  |  |  | Some difficulty/A lot of difficulty/Cannot do this at all | 2199 (27.4%) |
|  |  |  |  |  |  |  |
| 27 | SOC_SCWRKLIM | Work limited due to physical, mental, or emotional problem | categorical | 45 (0.6%) | No | 6281 (77.8%) |
|  |  |  |  |  | Yes | 1792 (22.2%) |
|  |  |  |  |  |  |  |
| 28 | SOCWRKLMT | DERIVED: Any social/work limitation | categorical | 78 (1.0%) | No | 5069 (63.0%) |
|  |  |  |  |  | Yes | 2971 (37.0%) |
|  |  |  |  |  |  |  |
| 29 | EMP_EMPLOY | Last week worked for pay at job or business | categorical | 22 (0.3%) | No | 3746 (46.3%) |
|  |  |  |  |  | Yes | 4350 (53.7%) |
|  |  |  |  |  |  |  |
| 30 | EMP_ABSENTWK | Had a job/business last week but temporarily absent | categorical | 4378 (53.9%) | No | 3516 (94.0%) |
|  |  |  |  |  | Yes | 224 (6.0%) |
|  |  |  |  |  |  |  |
| 31 | EMP_WHYNOWRK | Main reason not working for pay last week | categorical | 4634 (57.1%) | Unemployed, laid off, looking for work | 346 (9.9%) |
|  |  |  |  |  | Seasonal/contract work | 99 (2.8%) |
|  |  |  |  |  | Retired | 1850 (53.1%) |
|  |  |  |  |  | Unable to work for health reasons/disabled | 513 (14.7%) |
|  |  |  |  |  | Taking care of house or family | 333 (9.6%) |
|  |  |  |  |  | Going to school | 88 (2.5%) |
|  |  |  |  |  | Working at a family-owned job or business, but not for pay | 35 (1.0%) |
|  |  |  |  |  | Other | 220 (6.3%) |
|  |  |  |  |  |  |  |
| 32 | EMPWRKLSWK | DERIVED: Worked last week | categorical | 44 (0.5%) | Did not work | 3366 (41.7%) |
|  |  |  |  |  | Worked, Temp Absent, Seasonal, Family Job-no pay | 4708 (58.3%) |
|  |  |  |  |  |  |  |
| 33 | EMP_INSA | Insurance coverage: Self/family member employer, union | categorical | 233 (2.9%) | No | 3440 (43.6%) |
|  |  |  |  |  | Yes | 4440 (56.3%) |
|  |  |  |  |  | Upcoded: Yes | 5 (0.1%) |
|  |  |  |  |  |  |  |
| 34 | EMP_INSB | Insurance coverage: Self/family member purchased directly | categorical | 322 (4.0%) | No | 6331 (81.2%) |
|  |  |  |  |  | Yes | 1314 (16.9%) |
|  |  |  |  |  | Upcoded: Yes | 151 (1.9%) |
|  |  |  |  |  |  |  |
| 35 | EMP_INSC | Insurance coverage: Medicare | categorical | 259 (3.2%) | No | 5538 (70.5%) |
|  |  |  |  |  | Yes | 2299 (29.3%) |
|  |  |  |  |  | Upcoded: Yes | 22 (0.3%) |
|  |  |  |  |  |  |  |
| 36 | EMP_INSD | Insurance coverage: Medicaid or government assistance plan | categorical | 330 (4.1%) | No | 6452 (82.8%) |
|  |  |  |  |  | Yes | 1332 (17.1%) |
|  |  |  |  |  | Upcoded: Yes | 4 (0.1%) |
|  |  |  |  |  |  |  |
| 37 | EMP_INSE | Insurance coverage: TRICARE or other military | categorical | 331 (4.1%) | No | 7422 (95.3%) |
|  |  |  |  |  | Yes | 365 (4.7%) |
|  |  |  |  |  |  |  |
| 38 | EMP_INSF | Insurance coverage: VA health care | categorical | 308 (3.8%) | No | 7403 (94.8%) |
|  |  |  |  |  | Yes | 406 (5.2%) |
|  |  |  |  |  | Upcoded: Yes | 1 (0.0%) |
|  |  |  |  |  |  |  |
| 39 | EMP_INSG | Insurance coverage: Indian Health Service | categorical | 321 (4.0%) | No | 7698 (98.7%) |
|  |  |  |  |  | Yes | 99 (1.3%) |
|  |  |  |  |  |  |  |
| 40 | EMP_INSH | Insurance coverage: Any other | categorical | 527 (6.5%) | No | 7069 (93.1%) |
|  |  |  |  |  | Yes | 522 (6.9%) |
|  |  |  |  |  |  |  |
| 41 | EMP_INSH_UNK | Private insurance, Other/Unknown Source | categorical | 7596 (93.6%) | No | 387 (74.1%) |
|  |  |  |  |  | Upcoded: Yes | 135 (25.9%) |
|  |  |  |  |  |  |  |
| 42 | EMP_INSH_OTH | Other health insurance reported | categorical | 7596 (93.6%) | No | 441 (84.5%) |
|  |  |  |  |  | Upcoded: Yes | 81 (15.5%) |
|  |  |  |  |  |  |  |
| 43 | INSURED | DERIVED: Health Insurance Status | categorical | 37 (0.5%) | Not insured | 624 (7.7%) |
|  |  |  |  |  | Insured | 7457 (92.3%) |
|  |  |  |  |  |  |  |
| 44 | VET_AFVET | Ever served on active duty | categorical | 18 (0.2%) | No | 7352 (90.8%) |
|  |  |  |  |  | Yes | 748 (9.2%) |
|  |  |  |  |  |  |  |
| 45 | VET_AFVETTRN | Were on active duty only for training | categorical | 7383 (90.9%) | No | 590 (80.3%) |
|  |  |  |  |  | Yes | 145 (19.7%) |
|  |  |  |  |  |  |  |
| 46 | LYM_PREVA | Likely to get annual Lyme vaccine for preventing Lyme disease | categorical | 54 (0.7%) | Definitely | 1358 (16.8%) |
|  |  |  |  |  | Very likely | 1200 (14.9%) |
|  |  |  |  |  | Somewhat likely | 1856 (23.0%) |
|  |  |  |  |  | Somewhat unlikely | 1243 (15.4%) |
|  |  |  |  |  | Very unlikely | 1139 (14.1%) |
|  |  |  |  |  | Definitely not | 1268 (15.7%) |
|  |  |  |  |  |  |  |
| 47 | LYM_PREVB | Likely to take single dose antibiotics within 72 hours after tick bite | categorical | 67 (0.8%) | Definitely | 2530 (31.4%) |
|  |  |  |  |  | Very likely | 1788 (22.2%) |
|  |  |  |  |  | Somewhat likely | 1709 (21.2%) |
|  |  |  |  |  | Somewhat unlikely | 678 (8.4%) |
|  |  |  |  |  | Very unlikely | 618 (7.7%) |
|  |  |  |  |  | Definitely not | 728 (9.0%) |
|  |  |  |  |  |  |  |
| 48 | LYM_PREVC | Likely to use bug spray for preventing Lyme disease | categorical | 53 (0.7%) | Definitely | 2127 (26.4%) |
|  |  |  |  |  | Very likely | 2037 (25.3%) |
|  |  |  |  |  | Somewhat likely | 1999 (24.8%) |
|  |  |  |  |  | Somewhat unlikely | 686 (8.5%) |
|  |  |  |  |  | Very unlikely | 574 (7.1%) |
|  |  |  |  |  | Definitely not | 642 (8.0%) |
|  |  |  |  |  |  |  |
| 49 | LYM_PREVD | Likely to wear permethrin clothing for preventing Lyme disease | categorical | 58 (0.7%) | Definitely | 922 (11.4%) |
|  |  |  |  |  | Very likely | 1028 (12.8%) |
|  |  |  |  |  | Somewhat likely | 1876 (23.3%) |
|  |  |  |  |  | Somewhat unlikely | 1439 (17.9%) |
|  |  |  |  |  | Very unlikely | 1589 (19.7%) |
|  |  |  |  |  | Definitely not | 1206 (15.0%) |
|  |  |  |  |  |  |  |
| 50 | ACC_HTHLAST | Time since you last saw doctor about your health | categorical | 45 (0.6%) | Never | 138 (1.7%) |
|  |  |  |  |  | Less than 12 months ago | 6502 (80.5%) |
|  |  |  |  |  | More than 1 year but less than 2 years ago | 663 (8.2%) |
|  |  |  |  |  | More than 2 years but less than 3 years ago | 269 (3.3%) |
|  |  |  |  |  | More than 3 years but less than 5 years ago | 201 (2.5%) |
|  |  |  |  |  | More than 5 years but less than 10 years ago | 182 (2.3%) |
|  |  |  |  |  | 10 years ago or more | 118 (1.5%) |
|  |  |  |  |  |  |  |
| 51 | DOCVIS_P12M | RECODE: Doctor visit in past 12 months | categorical | 45 (0.6%) | Yes | 6502 (80.5%) |
|  |  |  |  |  | No | 1571 (19.5%) |
|  |  |  |  |  |  |  |
| 52 | ACC_HTHUSUAL | Have a usual place to go for health care | categorical | 29 (0.4%) | Yes, there is a single place | 4896 (60.5%) |
|  |  |  |  |  | No, there is no place | 755 (9.3%) |
|  |  |  |  |  | Yes, there is more than one place | 2438 (30.1%) |
|  |  |  |  |  |  |  |
| 53 | ACC_HTHTYPE | Type of place for usual care | categorical | 775 (9.5%) | I do not go to one place most often | 81 (1.1%) |
|  |  |  |  |  | A doctor’s office or health center | 6028 (82.1%) |
|  |  |  |  |  | Urgent care center or clinic in a drug store or grocery store | 766 (10.4%) |
|  |  |  |  |  | Hospital emergency room | 223 (3.0%) |
|  |  |  |  |  | A VA medical center or VA outpatient clinic | 180 (2.5%) |
|  |  |  |  |  | Some other place | 65 (0.9%) |
|  |  |  |  |  |  |  |
| 54 | ACC_RETAIL_R | RECODE: Past 12 months, number of retail health clinic visits - topcoded | categorical | 332 (4.1%) | 0 | 5544 (71.2%) |
|  |  |  |  |  | 1 | 1100 (14.1%) |
|  |  |  |  |  | 2 | 626 (8.0%) |
|  |  |  |  |  | 3 | 192 (2.5%) |
|  |  |  |  |  | 4 | 99 (1.3%) |
|  |  |  |  |  | 5 | 74 (1.0%) |
|  |  |  |  |  | 6 | 35 (0.4%) |
|  |  |  |  |  | 7 | 6 (0.1%) |
|  |  |  |  |  | 8 | 15 (0.2%) |
|  |  |  |  |  | 9 | 6 (0.1%) |
|  |  |  |  |  | (…) |  |
|  |  |  |  |  |  |  |
| 55 | ACC_URGENT_R | RECODE: Past 12 months, number of urgent care visits - topcoded | categorical | 299 (3.7%) | 0 | 5234 (66.9%) |
|  |  |  |  |  | 1 | 1578 (20.2%) |
|  |  |  |  |  | 2 | 616 (7.9%) |
|  |  |  |  |  | 3 | 201 (2.6%) |
|  |  |  |  |  | 4 | 69 (0.9%) |
|  |  |  |  |  | 5 | 51 (0.7%) |
|  |  |  |  |  | 6 | 27 (0.3%) |
|  |  |  |  |  | 7 | 8 (0.1%) |
|  |  |  |  |  | 8+ | 35 (0.4%) |
|  |  |  |  |  |  |  |
| 56 | URGENTCARE_P12M | RECODE: Urgent care visit in past 12 months | categorical | 299 (3.7%) | Yes | 2585 (33.1%) |
|  |  |  |  |  | No | 5234 (66.9%) |
|  |  |  |  |  |  |  |
| 57 | CIH_HLTH12M | Past 12 months, saw a traditional practitioner for health | categorical | 54 (0.7%) | No | 7911 (98.1%) |
|  |  |  |  |  | Yes | 153 (1.9%) |
|  |  |  |  |  |  |  |
| 58 | CIH_HOMEO | Past 12 months, saw a practitioner of Homeopathy for health | categorical | 47 (0.6%) | No | 7771 (96.3%) |
|  |  |  |  |  | Yes | 300 (3.7%) |
|  |  |  |  |  |  |  |
| 59 | CIH_REIKI | Past 12 months, saw a practitioner for energy healing/Reiki for health | categorical | 45 (0.6%) | No | 7890 (97.7%) |
|  |  |  |  |  | Yes | 183 (2.3%) |
|  |  |  |  |  |  |  |
| 60 | CIH_ACUPUN | Past 12 months, saw a practitioner for acupuncture for health | categorical | 52 (0.6%) | No | 7779 (96.4%) |
|  |  |  |  |  | Yes | 287 (3.6%) |
|  |  |  |  |  |  |  |
| 61 | CIH_ACU12M_R | RECODE: Past 12 months, number of acupuncture visits | categorical | 7837 (96.5%) | Only one time | 72 (25.6%) |
|  |  |  |  |  | 2-5 times | 100 (35.6%) |
|  |  |  |  |  | 6-10 times | 53 (18.9%) |
|  |  |  |  |  | 11+ times | 56 (19.9%) |
|  |  |  |  |  |  |  |
| 62 | CIH_ACUCOST | Past 12 months, acupuncture visits covered by insurance | categorical | 7834 (96.5%) | No | 165 (58.1%) |
|  |  |  |  |  | Yes | 119 (41.9%) |
|  |  |  |  |  |  |  |
| 63 | CIH_TAICHI | Past 12 months, practiced Tai Chi for health | categorical | 74 (0.9%) | No | 7847 (97.6%) |
|  |  |  |  |  | Yes | 197 (2.4%) |
|  |  |  |  |  |  |  |
| 64 | CIH_QIGONG | Past 12 months, practiced Qi Gong for health | categorical | 104 (1.3%) | No | 7900 (98.6%) |
|  |  |  |  |  | Yes | 114 (1.4%) |
|  |  |  |  |  |  |  |
| 65 | CIH_MUSART | Past 3 months, practiced music/art for health | categorical | 32 (0.4%) | No | 7108 (87.9%) |
|  |  |  |  |  | Yes | 978 (12.1%) |
|  |  |  |  |  |  |  |
| 66 | GLP_WEIGHT | Weight description | categorical | 22 (0.3%) | Very overweight | 1075 (13.3%) |
|  |  |  |  |  | Slightly overweight | 3597 (44.4%) |
|  |  |  |  |  | About the right weight | 2928 (36.2%) |
|  |  |  |  |  | Slightly underweight | 398 (4.9%) |
|  |  |  |  |  | Very underweight | 98 (1.2%) |
|  |  |  |  |  |  |  |
| 67 | GLP_LOSEWT | Past 12 months, doctor talked to you about losing weight | categorical | 34 (0.4%) | No | 5985 (74.0%) |
|  |  |  |  |  | Yes | 2099 (26.0%) |
|  |  |  |  |  |  |  |
| 68 | GLP_MED12M | Past 12 months, took GLP-1 medication for diabetes or weight loss | categorical | 28 (0.3%) | No | 7114 (87.9%) |
|  |  |  |  |  | Yes | 976 (12.1%) |
|  |  |  |  |  |  |  |
| 69 | GLP_MEDNOW | Currently taking GLP-1 medication | categorical | 7144 (88.0%) | No | 200 (20.5%) |
|  |  |  |  |  | Yes | 774 (79.5%) |
|  |  |  |  |  |  |  |
| 70 | GLP_MEDRX | Past 12 months, had prescription for GLP-1 medication | categorical | 7148 (88.1%) | No | 98 (10.1%) |
|  |  |  |  |  | Yes | 872 (89.9%) |
|  |  |  |  |  |  |  |
| 71 | GLP_MEDINFO | Prescribing professional provided nutrition information for GLP-1 medication | categorical | 7248 (89.3%) | No | 189 (21.7%) |
|  |  |  |  |  | Yes | 681 (78.3%) |
|  |  |  |  |  |  |  |
| 72 | GLP_MEDACT | Prescribing professional provided exercise information for GLP-1 medication | categorical | 7257 (89.4%) | No | 201 (23.3%) |
|  |  |  |  |  | Yes | 660 (76.7%) |
|  |  |  |  |  |  |  |
| 73 | GLP_RX12MA | Past 12 months, got GLP-1 medication from primary care doctor and filled at pharmacy | categorical | 7148 (88.1%) | No | 181 (18.7%) |
|  |  |  |  |  | Yes | 789 (81.3%) |
|  |  |  |  |  |  |  |
| 74 | GLP_RX12MB | Past 12 months, got GLP-1 medication from online provider that also helps plan a diet and exercise routine | categorical | 7162 (88.2%) | No | 871 (91.1%) |
|  |  |  |  |  | Yes | 85 (8.9%) |
|  |  |  |  |  |  |  |
| 75 | GLP_RX12MC | Past 12 months, got GLP-1 medication from online company that only provides medication | categorical | 7161 (88.2%) | No | 851 (88.9%) |
|  |  |  |  |  | Yes | 106 (11.1%) |
|  |  |  |  |  |  |  |
| 76 | GLP_RX12MD | Past 12 months, got GLP-1 medication from medical spa or cosmetic medical center | categorical | 7160 (88.2%) | No | 888 (92.7%) |
|  |  |  |  |  | Yes | 70 (7.3%) |
|  |  |  |  |  |  |  |
| 77 | GLP_RX12ME | Past 12 months, got GLP-1 medication from somewhere else | categorical | 7159 (88.2%) | No | 845 (88.1%) |
|  |  |  |  |  | Yes | 114 (11.9%) |
|  |  |  |  |  |  |  |
| 78 | GLP_COMPMED | Past 12 months, used a generic, compounded version of GLP-1 medication | categorical | 7224 (89.0%) | No | 681 (76.2%) |
|  |  |  |  |  | Yes | 213 (23.8%) |
|  |  |  |  |  |  |  |
| 79 | GLP_DOSEA | Past 12 months, skipped GLP-1 medication doses | categorical | 7146 (88.0%) | No | 650 (66.9%) |
|  |  |  |  |  | Yes | 322 (33.1%) |
|  |  |  |  |  |  |  |
| 80 | GLP_DOSEB | Past 12 months, took less GLP-1 medication than prescribed | categorical | 7147 (88.0%) | No | 763 (78.6%) |
|  |  |  |  |  | Yes | 208 (21.4%) |
|  |  |  |  |  |  |  |
| 81 | GLP_DOSEC | Past 12 months, delayed filling GLP-1 prescription | categorical | 7151 (88.1%) | No | 763 (78.9%) |
|  |  |  |  |  | Yes | 204 (21.1%) |
|  |  |  |  |  |  |  |
| 82 | GLP_DOSED | Past 12 months, stopped taking GLP-1 medication entirely | categorical | 7147 (88.0%) | No | 746 (76.8%) |
|  |  |  |  |  | Yes | 225 (23.2%) |
|  |  |  |  |  |  |  |
| 83 | GLP_DOSE | DERIVED: Any nonadherence with GLP-1 medication (skipped, reduced, delayed, or stopped dose) | categorical | 7149 (88.1%) | No | 516 (53.3%) |
|  |  |  |  |  | Yes | 453 (46.7%) |
|  |  |  |  |  |  |  |
| 84 | GLP_DOSEWHYA | Skipped GLP-1 medication doses because of cost | categorical | 7799 (96.1%) | No | 204 (63.9%) |
|  |  |  |  |  | Yes | 115 (36.1%) |
|  |  |  |  |  |  |  |
| 85 | GLP_DOSEWHYB | Skipped GLP-1 medication doses because not available | categorical | 7799 (96.1%) | No | 208 (65.2%) |
|  |  |  |  |  | Yes | 111 (34.8%) |
|  |  |  |  |  |  |  |
| 86 | GLP_LESSWHYA | Took less of GLP-1 medication because of cost | categorical | 7916 (97.5%) | No | 105 (52.0%) |
|  |  |  |  |  | Yes | 97 (48.0%) |
|  |  |  |  |  |  |  |
| 87 | GLP_LESSWHYB | Took less of GLP-1 medication because not available | categorical | 7916 (97.5%) | No | 126 (62.4%) |
|  |  |  |  |  | Yes | 76 (37.6%) |
|  |  |  |  |  |  |  |
| 88 | GLP_DELAYA | Delayed filling GLP-1 prescription because of cost | categorical | 7915 (97.5%) | No | 77 (37.9%) |
|  |  |  |  |  | Yes | 126 (62.1%) |
|  |  |  |  |  |  |  |
| 89 | GLP_DELAYB | Delayed filling GLP-1 prescription because not available | categorical | 7918 (97.5%) | No | 133 (66.5%) |
|  |  |  |  |  | Yes | 67 (33.5%) |
|  |  |  |  |  |  |  |
| 90 | GLP_STOPA | Stopped GLP-1 medication entirely because of cost | categorical | 7894 (97.2%) | No | 116 (51.8%) |
|  |  |  |  |  | Yes | 108 (48.2%) |
|  |  |  |  |  |  |  |
| 91 | GLP_STOPB | Stopped GLP-1 medication entirely because not available | categorical | 7897 (97.3%) | No | 164 (74.2%) |
|  |  |  |  |  | Yes | 57 (25.8%) |
|  |  |  |  |  |  |  |
| 92 | GLP_INSPAY | Past 12 months, insurance coverage level for GLP-1 medication | categorical | 7145 (88.0%) | None of the cost | 256 (26.3%) |
|  |  |  |  |  | Part of the cost | 470 (48.3%) |
|  |  |  |  |  | All of the cost | 247 (25.4%) |
|  |  |  |  |  |  |  |
| 93 | GLP_SYMPTOMS | Reduced or stopped GLP-1 medication due to side effects | categorical | 7147 (88.0%) | No | 808 (83.2%) |
|  |  |  |  |  | Yes | 163 (16.8%) |
|  |  |  |  |  |  |  |
| 94 | CIG_SMKEV | Smoked at least 100 cigarettes in entire life | categorical | 28 (0.3%) | No | 5203 (64.3%) |
|  |  |  |  |  | Yes | 2887 (35.7%) |
|  |  |  |  |  |  |  |
| 95 | CIG_AGE1_R | RECODE: Age when started smoking regularly | categorical | 5436 (67.0%) | Less than age 16 | 915 (34.1%) |
|  |  |  |  |  | Age 16 or older, less than age 20 | 1249 (46.6%) |
|  |  |  |  |  | Age 20 or older, less than age 25 | 370 (13.8%) |
|  |  |  |  |  | Age 25 or older, less than age 30 | 83 (3.1%) |
|  |  |  |  |  | Age 30 or older | 65 (2.4%) |
|  |  |  |  |  |  |  |
| 96 | CIG_SMKNOW | How often now smoke cigarettes | categorical | 5245 (64.6%) | Every day | 602 (21.0%) |
|  |  |  |  |  | Some days | 262 (9.1%) |
|  |  |  |  |  | Not at all | 2009 (69.9%) |
|  |  |  |  |  |  |  |
| 97 | SMK_STATUS | DERIVED: Smoking status: current, former, or never smoker | categorical | 42 (0.5%) | Smoked 100+ cigarettes and currently smokes | 864 (10.7%) |
|  |  |  |  |  | Smoked 100+ cigarettes but does not currently smoke | 2009 (24.9%) |
|  |  |  |  |  | Has not smoked 100 cigarettes in their lifetime | 5203 (64.4%) |
|  |  |  |  |  |  |  |
| 98 | CIG_AGE2_R | RECODE: Age last time you smoked regularly | categorical | 6043 (74.4%) | Less than age 16 | 24 (1.2%) |
|  |  |  |  |  | Age 16 or older, less than age 20 | 60 (2.9%) |
|  |  |  |  |  | Age 20 or older, less than age 25 | 306 (14.7%) |
|  |  |  |  |  | Age 25 or older, less than age 30 | 302 (14.6%) |
|  |  |  |  |  | Age 30 or older, less than age 35 | 291 (14.0%) |
|  |  |  |  |  | Age 35 or older, less than age 40 | 230 (11.1%) |
|  |  |  |  |  | Age 40 or older, less than age 45 | 240 (11.6%) |
|  |  |  |  |  | Age 45 or older, less than age 50 | 160 (7.7%) |
|  |  |  |  |  | Age 50 or older, less than age 55 | 173 (8.3%) |
|  |  |  |  |  | Age 55 or older, less than age 60 | 116 (5.6%) |
|  |  |  |  |  | (…) |  |
|  |  |  |  |  |  |  |
| 99 | CIG_YEARS_SMOKED_R | DERIVED: Number of years smoked cigarettes among current or former smokers | categorical | 5468 (67.4%) | Less than 5 | 219 (8.3%) |
|  |  |  |  |  | 5 or more, less than 10 | 339 (12.8%) |
|  |  |  |  |  | 10 or more, less than 15 | 316 (11.9%) |
|  |  |  |  |  | 15 or more, less than 20 | 313 (11.8%) |
|  |  |  |  |  | 20 or more, less than 25 | 286 (10.8%) |
|  |  |  |  |  | 25 or more, less than 30 | 263 (9.9%) |
|  |  |  |  |  | 30 or more, less than 35 | 223 (8.4%) |
|  |  |  |  |  | 35 or more, less than 40 | 188 (7.1%) |
|  |  |  |  |  | 40 or more, less than 45 | 171 (6.5%) |
|  |  |  |  |  | 45 or more, less than 50 | 130 (4.9%) |
|  |  |  |  |  | 50 or more | 202 (7.6%) |
|  |  |  |  |  |  |  |
| 100 | LUN_AVGCIG_R | RECODE: Average cigarettes per day ever smoked | categorical | 6087 (75.0%) | 1-9 | 917 (45.2%) |
|  |  |  |  |  | 10-29 | 1062 (52.3%) |
|  |  |  |  |  | 30+ | 52 (2.6%) |
|  |  |  |  |  |  |  |
| 101 | LUN_AVGCIG2_R | RECODE: Average cigarettes per day ever smoked - Follow up | categorical | 8108 (99.9%) | 1-9 | 6 (60.0%) |
|  |  |  |  |  | 10-29 | 3 (30.0%) |
|  |  |  |  |  | 30+ | 1 (10.0%) |
|  |  |  |  |  |  |  |
| 102 | LUN_AVGPACK_R | RECODE: Average packs per day ever smoked | categorical | 7315 (90.1%) | 1 | 606 (75.5%) |
|  |  |  |  |  | 2+ | 197 (24.5%) |
|  |  |  |  |  |  |  |
| 103 | LUN_AVGPACK2_R | RECODE: Average packs per day ever smoked - Follow up | categorical | 8114 (100.0%) | 1 | 3 (75.0%) |
|  |  |  |  |  | 2+ | 1 (25.0%) |
|  |  |  |  |  |  |  |
| 104 | AVG_PACKSPERDAY_R | DERIVED: Average number of packs of cigarettes smoked per day (1 pack = 20 cigarettes) | categorical | 5270 (64.9%) | 0 | 923 (32.4%) |
|  |  |  |  |  | 1 | 1674 (58.8%) |
|  |  |  |  |  | 2+ | 251 (8.8%) |
|  |  |  |  |  |  |  |
| 105 | LUNG_SCR_ELIG | DERIVED: Eligible for lung cancer screening (based on age and smoking history) | categorical | 6561 (80.8%) | Not eligible | 1003 (64.4%) |
|  |  |  |  |  | Eligible | 554 (35.6%) |
|  |  |  |  |  |  |  |
| 106 | LUN_DOCASK | Doctor ever asked if you smoke | categorical | 64 (0.8%) | No | 1356 (16.8%) |
|  |  |  |  |  | Yes | 6698 (83.2%) |
|  |  |  |  |  |  |  |
| 107 | LUN_NOTSHARE | Ever chose not to share smoking with doctor | categorical | 5458 (67.2%) | No | 2377 (89.4%) |
|  |  |  |  |  | Yes | 283 (10.6%) |
|  |  |  |  |  |  |  |
| 108 | LUN_INSUR | Did not share smoking to avoid negative effect on insurance cost | categorical | 7836 (96.5%) | No | 163 (57.8%) |
|  |  |  |  |  | Yes | 119 (42.2%) |
|  |  |  |  |  |  |  |
| 109 | LUN_JUDGED | Did not share smoking to avoid being negatively judged by doctor | categorical | 7836 (96.5%) | No | 90 (31.9%) |
|  |  |  |  |  | Yes | 192 (68.1%) |
|  |  |  |  |  |  |  |
| 110 | LUN_TREAT | Did not share smoking to avoid different treatment by doctor | categorical | 7836 (96.5%) | No | 126 (44.7%) |
|  |  |  |  |  | Yes | 156 (55.3%) |
|  |  |  |  |  |  |  |
| 111 | LUN_LECTURE | Did not share smoking to avoid lecture from doctor | categorical | 7836 (96.5%) | No | 73 (25.9%) |
|  |  |  |  |  | Yes | 209 (74.1%) |
|  |  |  |  |  |  |  |
| 112 | LUN_ASHAME | Did not share smoking because felt ashamed | categorical | 7839 (96.6%) | No | 116 (41.6%) |
|  |  |  |  |  | Yes | 163 (58.4%) |
|  |  |  |  |  |  |  |
| 113 | LUN_READY | Did not share smoking because not ready to quit | categorical | 7839 (96.6%) | No | 117 (41.9%) |
|  |  |  |  |  | Yes | 162 (58.1%) |
|  |  |  |  |  |  |  |
| 114 | LUN_SHOTHER | Did not share smoking for some other reason | categorical | 7845 (96.6%) | No | 179 (65.6%) |
|  |  |  |  |  | Yes | 94 (34.4%) |
|  |  |  |  |  |  |  |
| 115 | LUN_CANCER | Doctor ever said you had lung cancer | categorical | 74 (0.9%) | No | 7957 (98.9%) |
|  |  |  |  |  | Yes | 87 (1.1%) |
|  |  |  |  |  |  |  |
| 116 | LUN_LCSCREEN | Before survey, knew lung cancer screening recommendations | categorical | 39 (0.5%) | No | 6378 (78.9%) |
|  |  |  |  |  | Yes | 1701 (21.1%) |
|  |  |  |  |  |  |  |
| 117 | LUN_BENEFIT | Past 12 months, doctor discussed benefits of lung cancer scan | categorical | 2629 (32.4%) | No | 4928 (89.8%) |
|  |  |  |  |  | Yes | 561 (10.2%) |
|  |  |  |  |  |  |  |
| 118 | LUN_HARMS | Past 12 months, doctor discussed harms of lung cancer scan | categorical | 2758 (34.0%) | No | 5143 (96.0%) |
|  |  |  |  |  | Yes | 217 (4.0%) |
|  |  |  |  |  |  |  |
| 119 | LUN_LOWDOCT | Ever had low-dose CT scan of chest area | categorical | 2662 (32.8%) | No | 3609 (66.1%) |
|  |  |  |  |  | Yes | 1847 (33.9%) |
|  |  |  |  |  |  |  |
| 120 | LUN_CTSCREEN | Recent low-dose CT scan was for lung cancer screening | categorical | 6296 (77.6%) | No | 1391 (76.3%) |
|  |  |  |  |  | Yes | 431 (23.7%) |
|  |  |  |  |  |  |  |
| 121 | LUN_NOREC | No low-dose CT scan because doctor never recommended it | categorical | 3181 (39.2%) | No | 1620 (32.8%) |
|  |  |  |  |  | Yes | 3317 (67.2%) |
|  |  |  |  |  |  |  |
| 122 | LUN_HEALTHY | No low-dose CT scan because you are healthy | categorical | 3222 (39.7%) | No | 743 (15.2%) |
|  |  |  |  |  | Yes | 4153 (84.8%) |
|  |  |  |  |  |  |  |
| 123 | LUN_BLAMED | No low-dose CT scan because afraid of being judged for smoking | categorical | 6271 (77.2%) | No | 1742 (94.3%) |
|  |  |  |  |  | Yes | 105 (5.7%) |
|  |  |  |  |  |  |  |
| 124 | LUN_NOTIME | No low-dose CT scan because hard to find time to get screening | categorical | 3259 (40.1%) | No | 4622 (95.1%) |
|  |  |  |  |  | Yes | 237 (4.9%) |
|  |  |  |  |  |  |  |
| 125 | LUN_TRANSPO | No low-dose CT scan because hard to get transportation | categorical | 3212 (39.6%) | No | 4776 (97.4%) |
|  |  |  |  |  | Yes | 130 (2.6%) |
|  |  |  |  |  |  |  |
| 126 | LUN_EXPOSE | No low-dose CT scan because concerned about radiation exposure | categorical | 3206 (39.5%) | No | 4450 (90.6%) |
|  |  |  |  |  | Yes | 462 (9.4%) |
|  |  |  |  |  |  |  |
| 127 | LUN_CONCERN | No low-dose CT scan because concerned about other harms | categorical | 3214 (39.6%) | No | 4495 (91.7%) |
|  |  |  |  |  | Yes | 409 (8.3%) |
|  |  |  |  |  |  |  |
| 128 | LUN_NORISK | No low-dose CT scan because low lung cancer risk | categorical | 3234 (39.8%) | No | 1930 (39.5%) |
|  |  |  |  |  | Yes | 2954 (60.5%) |
|  |  |  |  |  |  |  |
| 129 | LUN_ANXIOUS | No low-dose CT scan because knowing results would cause anxiety | categorical | 3216 (39.6%) | No | 4357 (88.9%) |
|  |  |  |  |  | Yes | 545 (11.1%) |
|  |  |  |  |  |  |  |
| 130 | LUN_COST | No low-dose CT scan because of cost | categorical | 3216 (39.6%) | No | 3949 (80.6%) |
|  |  |  |  |  | Yes | 953 (19.4%) |
|  |  |  |  |  |  |  |
| 131 | LUN_SCOTHER | No low-dose CT scan because some other reason | categorical | 3258 (40.1%) | No | 4162 (85.6%) |
|  |  |  |  |  | Yes | 698 (14.4%) |
|  |  |  |  |  |  |  |
| 132 | LUN_BLAME | Believe people with lung cancer are to blame for their illness | categorical | 104 (1.3%) | Strongly agree | 269 (3.4%) |
|  |  |  |  |  | Somewhat agree | 2726 (34.0%) |
|  |  |  |  |  | Somewhat disagree | 3141 (39.2%) |
|  |  |  |  |  | Strongly disagree | 1878 (23.4%) |
|  |  |  |  |  |  |  |
| 133 | LUN_CHOICES | Believe people with lung cancer made poor lifestyle choices | categorical | 116 (1.4%) | Strongly agree | 380 (4.7%) |
|  |  |  |  |  | Somewhat agree | 3238 (40.5%) |
|  |  |  |  |  | Somewhat disagree | 2841 (35.5%) |
|  |  |  |  |  | Strongly disagree | 1543 (19.3%) |
|  |  |  |  |  |  |  |
| 134 | LUN_STILLRISK | Believe nonsmokers are still at risk of getting lung cancer | categorical | 102 (1.3%) | Strongly agree | 3446 (43.0%) |
|  |  |  |  |  | Somewhat agree | 3646 (45.5%) |
|  |  |  |  |  | Somewhat disagree | 660 (8.2%) |
|  |  |  |  |  | Strongly disagree | 264 (3.3%) |
|  |  |  |  |  |  |  |
| 135 | LUN_ASSUME | Assume if someone had lung cancer it is because they smoked | categorical | 94 (1.2%) | Strongly agree | 910 (11.3%) |
|  |  |  |  |  | Somewhat agree | 3964 (49.4%) |
|  |  |  |  |  | Somewhat disagree | 2122 (26.4%) |
|  |  |  |  |  | Strongly disagree | 1028 (12.8%) |
|  |  |  |  |  |  |  |
| 136 | HCA_DLYCOST | Past 12 months, delayed medical care due to cost | categorical | 38 (0.5%) | No | 6601 (81.7%) |
|  |  |  |  |  | Yes | 1479 (18.3%) |
|  |  |  |  |  |  |  |
| 137 | HCA_DNTCOST | Past 12 months, did not get medical care due to cost | categorical | 170 (2.1%) | No | 6720 (84.5%) |
|  |  |  |  |  | Yes | 1228 (15.5%) |
|  |  |  |  |  |  |  |
| 138 | MED_RX12MA | Past 12 months, took prescription medication | categorical | 87 (1.1%) | No | 2152 (26.8%) |
|  |  |  |  |  | Yes | 5879 (73.2%) |
|  |  |  |  |  |  |  |
| 139 | MED_RXSK12MA | Skipped medication to save money | categorical | 2247 (27.7%) | No | 5360 (91.3%) |
|  |  |  |  |  | Yes | 511 (8.7%) |
|  |  |  |  |  |  |  |
| 140 | MED_RXLS12MA | Took less medication to save money | categorical | 2258 (27.8%) | No | 5298 (90.4%) |
|  |  |  |  |  | Yes | 562 (9.6%) |
|  |  |  |  |  |  |  |
| 141 | MED_RXDL12MA | Delayed filling prescription to save money | categorical | 2252 (27.7%) | No | 5161 (88.0%) |
|  |  |  |  |  | Yes | 705 (12.0%) |
|  |  |  |  |  |  |  |
| 142 | MED_RXDG12MA | Past 12 months, needed but did not get medication because of cost | categorical | 67 (0.8%) | No | 7180 (89.2%) |
|  |  |  |  |  | Yes | 871 (10.8%) |
|  |  |  |  |  |  |  |
| 143 | INT_ACCESS | Access to internet | categorical | 0 (0.0%) | No | 97 (1.2%) |
|  |  |  |  |  | Yes | 8021 (98.8%) |
|  |  |  |  |  |  |  |
| 144 | INT_HOMEACC | Access to internet from home | categorical | 120 (1.5%) | No | 309 (3.9%) |
|  |  |  |  |  | Yes | 7689 (96.1%) |
|  |  |  |  |  |  |  |
| 145 | INT_USEMED | Past 12 months, use internet to look for health or medical information | categorical | 134 (1.7%) | No | 1813 (22.7%) |
|  |  |  |  |  | Yes | 6171 (77.3%) |
|  |  |  |  |  |  |  |
| 146 | INT_USEDOC | Past 12 months, use internet to communicate with doctor/doctor’s office | categorical | 146 (1.8%) | No | 2974 (37.3%) |
|  |  |  |  |  | Yes | 4998 (62.7%) |
|  |  |  |  |  |  |  |
| 147 | INT_USETEST | Past 12 months, use internet to look up medical test results | categorical | 145 (1.8%) | No | 2623 (32.9%) |
|  |  |  |  |  | Yes | 5350 (67.1%) |
|  |  |  |  |  |  |  |
| 148 | INT_USEHIT_R | DERIVED: Any health information technology (HIT) use | categorical | 133 (1.6%) | Yes | 6858 (85.9%) |
|  |  |  |  |  | No | 1127 (14.1%) |
|  |  |  |  |  |  |  |
| 149 | TEL_NONCELL | At least one telephone inside home, not cell phone | categorical | 32 (0.4%) | No | 5989 (74.1%) |
|  |  |  |  |  | Yes | 2097 (25.9%) |
|  |  |  |  |  |  |  |
| 150 | TEL_CELL | Have a working cell phone | categorical | 51 (0.6%) | No | 347 (4.3%) |
|  |  |  |  |  | Yes | 7720 (95.7%) |
|  |  |  |  |  |  |  |
| 151 | TEL_CELL_R | RECODE: Adult has a working cell phone | categorical | 51 (0.6%) | Yes | 7720 (95.7%) |
|  |  |  |  |  | No | 347 (4.3%) |
|  |  |  |  |  |  |  |
| 152 | TEL_HHCELL | Live with anyone with a working cell phone | categorical | 7843 (96.6%) | No | 144 (52.4%) |
|  |  |  |  |  | Yes | 131 (47.6%) |
|  |  |  |  |  |  |  |
| 153 | MTL_ANXIETY | How often feel worried, nervous or anxious | categorical | 55 (0.7%) | Never | 2332 (28.9%) |
|  |  |  |  |  | Daily | 1362 (16.9%) |
|  |  |  |  |  | Weekly | 1274 (15.8%) |
|  |  |  |  |  | Monthly | 891 (11.1%) |
|  |  |  |  |  | A few times a year | 2204 (27.3%) |
|  |  |  |  |  |  |  |
| 154 | MTL_ANXMEDS | Take prescription medications for worried, nervous or anxious feelings | categorical | 64 (0.8%) | No | 6553 (81.4%) |
|  |  |  |  |  | Yes | 1501 (18.6%) |
|  |  |  |  |  |  |  |
| 155 | MTL_ANXLVL | Last worried, nervous or anxious level | categorical | 2340 (28.8%) | A little | 2859 (49.5%) |
|  |  |  |  |  | A lot | 997 (17.3%) |
|  |  |  |  |  | Somewhere in between a little and a lot | 1922 (33.3%) |
|  |  |  |  |  |  |  |
| 156 | MTL_DEPRESS | How often feel depressed | categorical | 97 (1.2%) | Never | 3380 (42.1%) |
|  |  |  |  |  | Daily | 784 (9.8%) |
|  |  |  |  |  | Weekly | 780 (9.7%) |
|  |  |  |  |  | Monthly | 730 (9.1%) |
|  |  |  |  |  | A few times a year | 2347 (29.3%) |
|  |  |  |  |  |  |  |
| 157 | MTL_DEPMEDS | Take prescription medication for depression | categorical | 90 (1.1%) | No | 6820 (85.0%) |
|  |  |  |  |  | Yes | 1208 (15.0%) |
|  |  |  |  |  |  |  |
| 158 | MTL_DEPLVL | Last depression level | categorical | 3390 (41.8%) | A little | 2554 (54.0%) |
|  |  |  |  |  | A lot | 896 (19.0%) |
|  |  |  |  |  | Somewhere in between a little and a lot | 1278 (27.0%) |
|  |  |  |  |  |  |  |
| 159 | FER_PERAGE_R | RECODE: Age of first menstrual period - topcoded and bottomcoded | categorical | 8001 (98.6%) | \<=9 | 93 (79.5%) |
|  |  |  |  |  | 18+ | 24 (20.5%) |
|  |  |  |  |  |  |  |
| 160 | FER_PREG | Pregnant now | categorical | 6147 (75.7%) | No | 1917 (97.3%) |
|  |  |  |  |  | Yes | 54 (2.7%) |
|  |  |  |  |  |  |  |
| 161 | FER_PREGNUM_R | RECODE: Number of times been pregnant - topcoded | categorical | 6151 (75.8%) | 0 | 691 (35.1%) |
|  |  |  |  |  | 1 | 282 (14.3%) |
|  |  |  |  |  | 2 | 346 (17.6%) |
|  |  |  |  |  | 3 | 288 (14.6%) |
|  |  |  |  |  | 4 | 152 (7.7%) |
|  |  |  |  |  | 5+ | 208 (10.6%) |
|  |  |  |  |  |  |  |
| 162 | FER_LIVENUM_R | RECODE: Number of live births you have had - topcoded | categorical | 6862 (84.5%) | 0 | 118 (9.4%) |
|  |  |  |  |  | 1 | 336 (26.8%) |
|  |  |  |  |  | 2 | 398 (31.7%) |
|  |  |  |  |  | 3 | 227 (18.1%) |
|  |  |  |  |  | 4 | 95 (7.6%) |
|  |  |  |  |  | 5+ | 82 (6.5%) |
|  |  |  |  |  |  |  |
| 163 | FER_SURGERY | Ever had medical procedures that make it impossible to get pregnant or carry | categorical | 6220 (76.6%) | No | 1615 (85.1%) |
|  |  |  |  |  | Yes | 283 (14.9%) |
|  |  |  |  |  |  |  |
| 164 | FER_PHYSPOS | Physically able to have baby | categorical | 6523 (80.4%) | No | 316 (19.8%) |
|  |  |  |  |  | Yes | 1279 (80.2%) |
|  |  |  |  |  |  |  |
| 165 | FER_PLANS | Want to have baby in future | categorical | 6119 (75.4%) | Definitely yes | 393 (19.7%) |
|  |  |  |  |  | Probably yes | 383 (19.2%) |
|  |  |  |  |  | Probably no | 373 (18.7%) |
|  |  |  |  |  | Definitely no | 850 (42.5%) |
|  |  |  |  |  |  |  |
| 166 | FER_INTEND | Intend to have baby in future | categorical | 6798 (83.7%) | No | 847 (64.2%) |
|  |  |  |  |  | Yes | 473 (35.8%) |
|  |  |  |  |  |  |  |
| 167 | FER_EXPECT | When expect your child to be born | categorical | 7653 (94.3%) | Within the next 2 years | 157 (33.8%) |
|  |  |  |  |  | 2-5 years from now | 212 (45.6%) |
|  |  |  |  |  | More than 5 years from now | 96 (20.6%) |
|  |  |  |  |  |  |  |
| 168 | FER_SEXMALE | Ever had sex with male | categorical | 7435 (91.6%) | No | 227 (33.2%) |
|  |  |  |  |  | Yes | 456 (66.8%) |
|  |  |  |  |  |  |  |
| 169 | FER_SEXM12M | Past 12 months, had sex with male | categorical | 6406 (78.9%) | No | 308 (18.0%) |
|  |  |  |  |  | Yes | 1404 (82.0%) |
|  |  |  |  |  |  |  |
| 170 | FER_PREVENT | Used method to prevent pregnancy last time you had sex with male | categorical | 6717 (82.7%) | No | 495 (35.3%) |
|  |  |  |  |  | Yes | 906 (64.7%) |
|  |  |  |  |  |  |  |
| 171 | FER_WANTPREG | No birth control method used because wanted to become pregnant | categorical | 7624 (93.9%) | No | 368 (74.5%) |
|  |  |  |  |  | Yes | 126 (25.5%) |
|  |  |  |  |  |  |  |
| 172 | FER_WHYNOBC | Main reason did not use birth control | categorical | 7756 (95.5%) | You did not expect to have sex | 16 (4.4%) |
|  |  |  |  |  | You did not think you could get pregnant | 70 (19.3%) |
|  |  |  |  |  | You didn’t really mind if you got pregnant | 54 (14.9%) |
|  |  |  |  |  | You were worried about the side effects of birth control | 20 (5.5%) |
|  |  |  |  |  | Your male partner did not want you to use a birth control method | 3 (0.8%) |
|  |  |  |  |  | Your male partner himself did not want to use a birth control method | 5 (1.4%) |
|  |  |  |  |  | Other reason | 194 (53.6%) |
|  |  |  |  |  |  |  |
| 173 | FER_BCDOC | Past 12 months, received method of birth control or prescription from a doctor | categorical | 6125 (75.4%) | No | 1436 (72.1%) |
|  |  |  |  |  | Yes | 557 (27.9%) |
|  |  |  |  |  |  |  |
| 174 | FER_TESTBC | Past 12 months, had checkup or medical test for birth control method | categorical | 6126 (75.5%) | No | 1582 (79.4%) |
|  |  |  |  |  | Yes | 410 (20.6%) |
|  |  |  |  |  |  |  |
| 175 | FER_INFOBC | Past 12 months, received birth control counseling or information | categorical | 6134 (75.6%) | No | 1571 (79.2%) |
|  |  |  |  |  | Yes | 413 (20.8%) |
|  |  |  |  |  |  |  |
| 176 | FER_INFOSTER | Past 12 months, received sterilization counseling or information | categorical | 6121 (75.4%) | No | 1878 (94.0%) |
|  |  |  |  |  | Yes | 119 (6.0%) |
|  |  |  |  |  |  |  |
| 177 | FER_PLANB | Past 12 months, received emergency contraception, counseling or information | categorical | 6122 (75.4%) | No | 1893 (94.8%) |
|  |  |  |  |  | Yes | 103 (5.2%) |
|  |  |  |  |  |  |  |
| 178 | FER_PAPTEST | Past 12 months, received a Pap test | categorical | 6124 (75.4%) | No | 1177 (59.0%) |
|  |  |  |  |  | Yes | 817 (41.0%) |
|  |  |  |  |  |  |  |
| 179 | FER_PELVEXAM | Past 12 months, received a pelvic exam | categorical | 6143 (75.7%) | No | 1126 (57.0%) |
|  |  |  |  |  | Yes | 849 (43.0%) |
|  |  |  |  |  |  |  |
| 180 | FER_STDTEST | Past 12 months, tested for a sexually transmitted disease | categorical | 6115 (75.3%) | No | 1437 (71.7%) |
|  |  |  |  |  | Yes | 566 (28.3%) |
|  |  |  |  |  |  |  |
| 181 | FER_FERTILITY | Ever gone to doctor to talk about ways to help get pregnant | categorical | 6137 (75.6%) | No | 1726 (87.1%) |
|  |  |  |  |  | Yes | 255 (12.9%) |
|  |  |  |  |  |  |  |
| 182 | FER_FERTNOW | Currently pursuing medical help to get pregnant | categorical | 7863 (96.9%) | No | 220 (86.3%) |
|  |  |  |  |  | Yes | 35 (13.7%) |
|  |  |  |  |  |  |  |
| 183 | FER_DOCPREV | Ever gone to doctor to help prevent miscarriage | categorical | 6129 (75.5%) | No | 1839 (92.5%) |
|  |  |  |  |  | Yes | 150 (7.5%) |
|  |  |  |  |  |  |  |
| 184 | BMICAT6 | RECODE: Body Mass Index - 6 levels | categorical | 338 (4.2%) | Underweight | 175 (2.2%) |
|  |  |  |  |  | Healthy weight | 2307 (29.7%) |
|  |  |  |  |  | Overweight | 2433 (31.3%) |
|  |  |  |  |  | Class 1 Obesity | 1514 (19.5%) |
|  |  |  |  |  | Class 2 Obesity | 737 (9.5%) |
|  |  |  |  |  | Class 3 Obesity | 614 (7.9%) |
|  |  |  |  |  |  |  |
| 185 | MAR_MARITAL | Now married, living with a partner, or neither | categorical | 43 (0.5%) | Married | 4231 (52.4%) |
|  |  |  |  |  | Living with a partner together as an unmarried couple | 883 (10.9%) |
|  |  |  |  |  | Neither | 2961 (36.7%) |
|  |  |  |  |  |  |  |
| 186 | MAR_EVMARRY | Ever been married | categorical | 4265 (52.5%) | No | 2300 (59.7%) |
|  |  |  |  |  | Yes | 1553 (40.3%) |
|  |  |  |  |  |  |  |
| 187 | MAR_LEGAL | Current legal marital status | categorical | 7817 (96.3%) | Married | 14 (4.7%) |
|  |  |  |  |  | Widowed | 42 (14.0%) |
|  |  |  |  |  | Divorced | 226 (75.1%) |
|  |  |  |  |  | Separated | 19 (6.3%) |
|  |  |  |  |  |  |  |
| 188 | MAR_WIDIVSEP | Widowed, divorced, or separated | categorical | 6883 (84.8%) | Widowed | 406 (32.9%) |
|  |  |  |  |  | Divorced | 761 (61.6%) |
|  |  |  |  |  | Separated | 68 (5.5%) |
|  |  |  |  |  |  |  |
| 189 | MARITAL | DERIVED: Current Marriage Status - 2 levels | categorical | 59 (0.7%) | Married | 4231 (52.5%) |
|  |  |  |  |  | Not married | 3828 (47.5%) |
|  |  |  |  |  |  |  |
| 190 | MARSTAT | DERIVED: Current marital status | categorical | 59 (0.7%) | Married | 4231 (52.5%) |
|  |  |  |  |  | Widowed | 406 (5.0%) |
|  |  |  |  |  | Divorced | 761 (9.4%) |
|  |  |  |  |  | Separated | 68 (0.8%) |
|  |  |  |  |  | Never Married | 1710 (21.2%) |
|  |  |  |  |  | Living with partner | 883 (11.0%) |
|  |  |  |  |  |  |  |
| 191 | LEGMSTAT | DERIVED: Legal marital status | categorical | 59 (0.7%) | Separated | 87 (1.1%) |
|  |  |  |  |  | Divorced | 987 (12.2%) |
|  |  |  |  |  | Married | 4245 (52.7%) |
|  |  |  |  |  | Single/Never Married | 2292 (28.4%) |
|  |  |  |  |  | Widowed | 448 (5.6%) |
|  |  |  |  |  |  |  |
| 192 | LAN_OTHERLAN | Speak language other than English at home | categorical | 68 (0.8%) | No | 6505 (80.8%) |
|  |  |  |  |  | Yes | 1545 (19.2%) |
|  |  |  |  |  |  |  |
| 193 | LAN_MEDIA | Language used most often when watching television, reading news, or listening to radio | categorical | 6577 (81.0%) | English | 900 (58.4%) |
|  |  |  |  |  | Spanish | 505 (32.8%) |
|  |  |  |  |  | Another language | 136 (8.8%) |
|  |  |  |  |  |  |  |
| 194 | LAN_DOCTOR | Language used most often when seeing a doctor | categorical | 6601 (81.3%) | English | 1222 (80.6%) |
|  |  |  |  |  | Spanish | 261 (17.2%) |
|  |  |  |  |  | Another language | 34 (2.2%) |
|  |  |  |  |  |  |  |
| 195 | LAN_SOCIAL | Language used most often when participating in social activities | categorical | 6588 (81.2%) | English | 1107 (72.4%) |
|  |  |  |  |  | Spanish | 357 (23.3%) |
|  |  |  |  |  | Another language | 66 (4.3%) |
|  |  |  |  |  |  |  |
| 196 | DEM_RACEETH | DERIVED: Race/ethnicity | categorical | 102 (1.3%) | American Indian or Alaska Native alone | 60 (0.7%) |
|  |  |  |  |  | Asian alone | 367 (4.6%) |
|  |  |  |  |  | Black alone | 892 (11.1%) |
|  |  |  |  |  | Hispanic or Latino alone | 866 (10.8%) |
|  |  |  |  |  | Middle Eastern alone | 22 (0.3%) |
|  |  |  |  |  | Native Hawaiian or Pacific Islander alone | 17 (0.2%) |
|  |  |  |  |  | White alone | 5217 (65.1%) |
|  |  |  |  |  | Multiracial and/or Multiethnic | 575 (7.2%) |
|  |  |  |  |  |  |  |
| 197 | DEM_REGION | DERIVED: Census Region | categorical | 117 (1.4%) | Northeast | 1225 (15.3%) |
|  |  |  |  |  | Midwest | 1836 (22.9%) |
|  |  |  |  |  | South | 2960 (37.0%) |
|  |  |  |  |  | West | 1980 (24.7%) |
|  |  |  |  |  |  |  |
| 198 | LYME_REGION | RECODE: Lyme disease incidence classification based on respondent’s state | categorical | 117 (1.4%) | High Lyme disease incidence | 2055 (25.7%) |
|  |  |  |  |  | Emerging Lyme disease incidence | 1733 (21.7%) |
|  |  |  |  |  | Low Lyme disease incidence | 4213 (52.7%) |
|  |  |  |  |  |  |  |
| 199 | CIV_VOL12M | Past 12 months, spend any time volunteering | categorical | 63 (0.8%) | No | 5611 (69.7%) |
|  |  |  |  |  | Yes | 2444 (30.3%) |
|  |  |  |  |  |  |  |
| 200 | CIV_VOLOTH | Past 12 months, activities at schools or youth organizations | categorical | 2552 (31.4%) | No | 5174 (93.0%) |
|  |  |  |  |  | Yes | 392 (7.0%) |
|  |  |  |  |  |  |  |
| 201 | CIV_MEET | Past 12 months, attend local public meeting | categorical | 117 (1.4%) | No | 6990 (87.4%) |
|  |  |  |  |  | Yes | 1011 (12.6%) |
|  |  |  |  |  |  |  |
| 202 | CIV_VOTELOCL | Vote in last local elections | categorical | 133 (1.6%) | No | 3265 (40.9%) |
|  |  |  |  |  | Yes | 4720 (59.1%) |
|  |  |  |  |  |  |  |
| 203 | CIVIC_ENGAGE | DERIVED: Civic engagement including volunteering | categorical | 157 (1.9%) | Yes | 5487 (68.9%) |
|  |  |  |  |  | No | 2474 (31.1%) |
|  |  |  |  |  |  |  |
| 204 | SOURCE | Paradata: Panel Provider | categorical | 0 (0.0%) | Panel Provider 1 | 4106 (50.6%) |
|  |  |  |  |  | Panel Provider 2 | 4012 (49.4%) |
|  |  |  |  |  |  |  |
| 205 | QUEX_LANG | Paradata: Language of interview | categorical | 0 (0.0%) | English | 7839 (96.6%) |
|  |  |  |  |  | Spanish | 279 (3.4%) |
|  |  |  |  |  |  |  |
| 206 | P_OUTCOME | Paradata: Outcome code | categorical | 0 (0.0%) | Complete (reached last question) | 8118 (100.0%) |
|  |  |  |  |  |  |  |
| 207 | P_HHSIZE_R | Panel Profile: Numeric Household Size Recode, capped at 6+ | categorical | 0 (0.0%) | 1 | 1453 (17.9%) |
|  |  |  |  |  | 2 | 2868 (35.3%) |
|  |  |  |  |  | 3 | 1492 (18.4%) |
|  |  |  |  |  | 4 | 1134 (14.0%) |
|  |  |  |  |  | 5 | 605 (7.5%) |
|  |  |  |  |  | 6+ | 566 (7.0%) |
|  |  |  |  |  |  |  |
| 208 | P_AGE5YRS_R | Panel Profile: Age Recode - 12 levels | categorical | 0 (0.0%) | 18-19 | 176 (2.2%) |
|  |  |  |  |  | 20-24 | 407 (5.0%) |
|  |  |  |  |  | 25-29 | 603 (7.4%) |
|  |  |  |  |  | 30-34 | 767 (9.4%) |
|  |  |  |  |  | 35-39 | 655 (8.1%) |
|  |  |  |  |  | 40-44 | 760 (9.4%) |
|  |  |  |  |  | 45-49 | 614 (7.6%) |
|  |  |  |  |  | 50-54 | 601 (7.4%) |
|  |  |  |  |  | 55-59 | 670 (8.3%) |
|  |  |  |  |  | 60-64 | 765 (9.4%) |
|  |  |  |  |  | (…) |  |
|  |  |  |  |  |  |  |
| 209 | P_SEX | Panel Profile: Respondent’s sex | categorical | 0 (0.0%) | Male | 3914 (48.2%) |
|  |  |  |  |  | Female | 4204 (51.8%) |
|  |  |  |  |  |  |  |
| 210 | P_EDUCATION_I_R | Panel Profile: Education recode - 3 levels | categorical | 0 (0.0%) | High school graduate or less | 2403 (29.6%) |
|  |  |  |  |  | Some college | 2579 (31.8%) |
|  |  |  |  |  | Bachelor’s degree or above | 3136 (38.6%) |
|  |  |  |  |  |  |  |
| 211 | P_EDUCATION_I_R_IFLG | Imputation flag for panel profile variable: | categorical | 0 (0.0%) | No imputation | 8101 (99.8%) |
|  |  |  |  |  | Statistical imputation | 17 (0.2%) |
|  |  |  |  |  |  |  |
| 212 | P_ONEVISIT | Paradata: Whether the survey was completed in a single session | categorical | 0 (0.0%) | Multiple session or did not complete | 1465 (18.0%) |
|  |  |  |  |  | Completed survey in single session | 6653 (82.0%) |
|  |  |  |  |  |  |  |
| 213 | P_REMIND | Paradata: Number of reminders sent | categorical | 0 (0.0%) | 0 | 5373 (66.2%) |
|  |  |  |  |  | 1 | 1170 (14.4%) |
|  |  |  |  |  | 2 | 621 (7.6%) |
|  |  |  |  |  | 3 | 325 (4.0%) |
|  |  |  |  |  | 4 | 230 (2.8%) |
|  |  |  |  |  | 5 | 169 (2.1%) |
|  |  |  |  |  | 6 | 93 (1.1%) |
|  |  |  |  |  | 7 | 82 (1.0%) |
|  |  |  |  |  | 8 | 48 (0.6%) |
|  |  |  |  |  | 9 | 7 (0.1%) |
|  |  |  |  |  |  |  |
| 214 | P_DEVICE | Paradata: Device used to complete survey | categorical | 0 (0.0%) | Desktop/Laptop/netbook | 2728 (33.6%) |
|  |  |  |  |  | Smartphone | 4808 (59.2%) |
|  |  |  |  |  | Tablet | 165 (2.0%) |
|  |  |  |  |  | Phone interview (not online) | 417 (5.1%) |
|  |  |  |  |  |  |  |
| 215 | P_MODE | Paradata: Mode of interview | categorical | 0 (0.0%) | Web | 7701 (94.9%) |
|  |  |  |  |  | CATI | 417 (5.1%) |
|  |  |  |  |  |  |  |
| 216 | P_POVERTY4_R | Panel Profile: Poverty Status Recode (ratio of household income to the federal poverty level) - 4 levels | categorical | 0 (0.0%) | 0 - \< 1.00 | 1048 (12.9%) |
|  |  |  |  |  | 1.00 - \< 2.00 | 1379 (17.0%) |
|  |  |  |  |  | 2.00 - \< 4.00 | 2455 (30.2%) |
|  |  |  |  |  | 4.00 + | 3236 (39.9%) |
|  |  |  |  |  |  |  |
| 217 | NCHS_METRO | RECODE: Metropolitan status | categorical | 0 (0.0%) | Metro Area | 6903 (85.0%) |
|  |  |  |  |  | Non-Metro Area | 1215 (15.0%) |
|  |  |  |  |  |  |  |
| 218 | P_HOMEOWN_R | Panel Profile: Home Ownership Recode - 2 levels | categorical | 0 (0.0%) | Own or being bought | 5626 (69.3%) |
|  |  |  |  |  | Rent/other arrangement | 2492 (30.7%) |
|  |  |  |  |  |  |  |
| 219 | P_CITIZEN | Panel Profile: Are you a US citizen | categorical | 358 (4.4%) | Not a U.S. citizen | 291 (3.8%) |
|  |  |  |  |  | U.S. citizen | 7469 (96.2%) |
|  |  |  |  |  |  |  |
| 220 | P_USBORN | Panel Profile: Is respondent US born | categorical | 668 (8.2%) | No | 598 (8.0%) |
|  |  |  |  |  | Yes | 6852 (92.0%) |
|  |  |  |  |  |  |  |
| 221 | P_ORIENT | Panel Profile: Sexual Orientation | categorical | 679 (8.4%) | Gay or lesbian | 245 (3.3%) |
|  |  |  |  |  | Straight, that is not lesbian/gay | 6713 (90.2%) |
|  |  |  |  |  | Bisexual | 353 (4.7%) |
|  |  |  |  |  | Something else | 128 (1.7%) |
|  |  |  |  |  |  |  |

rss7 (8118 rows and 224 variables, 221 shown) {.table}
